name: 'Update JetBrains Plugin Platform Version'

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  update-jetbrains-plugin-platform-version:
    runs-on: ubuntu-latest
    steps:
      # Harden the runner
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        timeout-minutes: 1
        with:
          token: ${{ secrets.PAT_TOKEN_FOR_IJ_UPDATE_ACTION }}

      - uses: ChrisCarini/gh-test-ij-release-update-action@main
        with:
          PAT_TOKEN_FOR_IJ_UPDATE_ACTION: ${{ secrets.PAT_TOKEN_FOR_IJ_UPDATE_ACTION }}
